name: clean files

on:
  schedule:
    - cron: '0 */1 * * *' #每1小时运行一次
  workflow_dispatch: #手动运行

jobs:
  collect-data:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Run clean files
        run: |
          python clean_files.py
      
      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          timestamp = $(date -u +"%Y-%m-%d %H:%M:%S UTC")
          git commit -m "Clean files by github actions at $timestamp"
          git push